const IS_DEV = process.env.APP_VARIANT === 'development'

module.exports = {
    expo: {
        name: IS_DEV ? 'KenkoAssist (DEV)' : 'KenkoAssist',
        newArchEnabled: true,
        slug: 'KenkoAssist',
        version: '0.1.0',
        orientation: 'default',
        icon: './assets/images/icon.png',
        scheme: 'KenkoAssist',
        userInterfaceStyle: 'automatic',
        assetBundlePatterns: ['**/*'],
        ios: {
            icon: {
                dark: './assets/images/ios-dark.png',
                light: './assets/images/ios-light.png',
                tinted: './assets/images/icon.png',
            },
            supportsTablet: true,
            package: IS_DEV ? 'com.johnjehiel.KenkoAssistDev' : 'com.johnjehiel.KenkoAssist',
            bundleIdentifier: IS_DEV ? 'com.johnjehiel.KenkoAssistDev' : 'com.johnjehiel.KenkoAssist',
        },
        android: {
            adaptiveIcon: {
                foregroundImage: './assets/images/adaptive-icon-foreground.png',
                backgroundImage: './assets/images//adaptive-icon-background.png',
                monochromeImage: './assets/images/adaptive-icon-foreground.png',
                backgroundColor: '#000',
            },
            package: IS_DEV ? 'com.johnjehiel.KenkoAssistDev' : 'com.johnjehiel.KenkoAssist',
            userInterfaceStyle: 'dark',
            permissions: [
                "android.permission.FOREGROUND_SERVICE",
                "android.permission.WAKE_LOCK",
                "android.permission.FOREGROUND_SERVICE_DATA_SYNC",
                "android.permission.health.READ_ACTIVE_CALORIES_BURNED",
                "android.permission.health.READ_BASAL_BODY_TEMPERATURE",
                "android.permission.health.READ_BASAL_METABOLIC_RATE",
                "android.permission.health.READ_BLOOD_GLUCOSE",
                "android.permission.health.READ_BLOOD_PRESSURE",
                "android.permission.health.READ_BODY_FAT",
                "android.permission.health.READ_BODY_TEMPERATURE",
                "android.permission.health.READ_BODY_WATER_MASS",
                "android.permission.health.READ_BONE_MASS",
                "android.permission.health.READ_CERVICAL_MUCUS",
                "android.permission.health.READ_CYCLING_PEDALING_CADENCE",
                "android.permission.health.READ_DISTANCE",
                "android.permission.health.READ_ELEVATION_GAINED",
                "android.permission.health.READ_EXERCISE",
                "android.permission.health.READ_FLOORS_CLIMBED",
                "android.permission.health.READ_HEART_RATE",
                "android.permission.health.READ_HEART_RATE_VARIABILITY",
                "android.permission.health.READ_HEIGHT",
                "android.permission.health.READ_HYDRATION",
                "android.permission.health.READ_LEAN_BODY_MASS",
                "android.permission.health.READ_MENSTRUATION",
                "android.permission.health.READ_NUTRITION",
                "android.permission.health.READ_OVULATION_TEST",
                "android.permission.health.READ_OXYGEN_SATURATION",
                "android.permission.health.READ_POWER",
                "android.permission.health.READ_RESPIRATORY_RATE",
                "android.permission.health.READ_RESTING_HEART_RATE",
                "android.permission.health.READ_SEXUAL_ACTIVITY",
                "android.permission.health.READ_SLEEP",
                "android.permission.health.READ_SPEED",
                "android.permission.health.READ_STEPS",
                "android.permission.health.READ_STEPS_CADENCE",
                "android.permission.health.READ_TOTAL_CALORIES_BURNED",
                "android.permission.health.READ_VO2_MAX",
                "android.permission.health.READ_WEIGHT",
                "android.permission.health.READ_WHEELCHAIR_PUSHES",
            ],
        },
        web: {
            bundler: 'metro',
            output: 'static',
            favicon: './assets/images/adaptive-icon.png',
        },
        plugins: [
            [
                'expo-asset',
                {
                    assets: ['./assets/models/aibot.png', './assets/models/llama3tokenizer.gguf'],
                },
            ],
            [
                'expo-build-properties',
                {
                    android: {
                        largeHeap: true,
                        usesCleartextTraffic: true,
                        enableProguardInReleaseBuilds: true,
                        enableShrinkResourcesInReleaseBuilds: true,
                        useLegacyPackaging: true,
                        extraProguardRules: '-keep class com.rnllama.** { *; }',
                        "compileSdkVersion": 35,
                        "targetSdkVersion": 35,
                        "minSdkVersion": 26,
                    },
                },
            ],
            [
                'expo-splash-screen',
                {
                    backgroundColor: '#000000',
                    image: './assets/images/adaptive-icon.png',
                    imageWidth: 200,
                },
            ],
            [
                'expo-notifications',
                {
                    icon: './assets/images/notification.png',
                },
            ],
            [
                './expo-build-plugins/androidattributes.plugin.js',
                {
                    'android:largeHeap': true,
                },
            ],
            'expo-localization',
            'expo-router',
            'expo-sqlite',
            'expo-health-connect',
            './expo-build-plugins/androidManifestPlugin.js',
            './expo-build-plugins/bgactions.plugin.js',
            './expo-build-plugins/copyjni.plugin.js',
            './expo-build-plugins/usercert.plugin.js',
        ],
        experiments: {
            typedRoutes: true,
        },
        extra: {
            router: {
                origin: false,
            },
            eas: {
                projectId: '43c7e715-3ae7-4625-9027-25247e73e7e9',
            },
        },
    },
}

