export const labelMap: Record<string, string> = {
  steps: 'Steps',
  distance: 'Distance',
  floorsClimbed: 'Floors Climbed',
  activeCalories: 'Active Calories',
  totalCalories: 'Total Calories',
  basalMetabolicRate: 'BMR',
  heartRate: 'Heart Rate',
  restingHeartRate: 'Resting HR',
  heartRateVariability: 'HRV',
  weight: 'Weight',
  height: 'Height',
  bodyFat: 'Body Fat',
  hydration: 'Hydration',
  boneMass: 'Bone Mass',
  leanBodyMass: 'Lean Mass',
  bodyWaterMass: 'Water Mass',
  bloodGlucose: 'Blood Glucose',
  bloodPressureSystolic: 'BP Systolic',
  bloodPressureDiastolic: 'BP Diastolic',
  bodyTemperature: 'Body Temp',
  basalBodyTemperature: 'Basal Temp',
  vo2Max: 'VO2 Max',
  respiratoryRate: 'Breathing Rate',
  oxygenSaturation: 'O2 Saturation',
  power: 'Power',
  speed: 'Speed',
  stepsCadence: 'Steps Cadence',
  cyclingCadence: 'Cycling Cadence',
  elevationGained: 'Elevation',
  wheelchairPushes: 'Wheelchair Pushes',
  exerciseSessions: 'Exercise Sessions',
  sleepSessions: 'Sleep Sessions',
  sexualActivity: 'Sexual Activity',
  menstruationPeriods: 'Menstruation',
  intermenstrualBleeding: 'Intermenstrual',
  cervicalMucus: 'Cervical Mucus',
  ovulationTest: 'Ovulation Tests'
};

export const healthCategories = {
  physicalActivity: {
    name: 'Physical Activity & Movement',
    metrics: ['steps', 'distance', 'floorsClimbed', 'activeCalories', 'totalCalories', 'exerciseSessions'],
  },
  cardiovascularHealth: {
    name: 'Cardiovascular Health',
    metrics: ['heartRate', 'restingHeartRate', 'heartRateVariability', 'bloodPressureSystolic', 'bloodPressureDiastolic'],
  },
  bodyComposition: {
    name: 'Body Composition & Physical Metrics',
    metrics: ['weight', 'height', 'bodyFat', 'leanBodyMass', 'bodyWaterMass', 'boneMass'],
  },
  metabolicHealth: {
    name: 'Metabolic & Vital Signs',
    metrics: ['bloodGlucose', 'basalMetabolicRate', 'bodyTemperature', 'basalBodyTemperature'],
  },
  respiratoryFitness: {
    name: 'Respiratory & Fitness Performance',
    metrics: ['vo2Max', 'respiratoryRate', 'oxygenSaturation'],
  },
  hydrationNutrition: {
    name: 'Hydration & Nutrition',
    metrics: ['hydration'],
  },
  performanceMetrics: {
    name: 'Performance & Activity Details',
    metrics: ['power', 'speed', 'stepsCadence', 'cyclingCadence', 'elevationGained', 'wheelchairPushes'],
  },
  reproductiveHealth: {
    name: 'Reproductive & Sexual Health',
    metrics: ['sexualActivity', 'menstruationPeriods', 'intermenstrualBleeding', 'cervicalMucus', 'ovulationTest'],
  },
  sleepRecovery: {
    name: 'Sleep & Recovery',
    metrics: ['sleepSessions'],
  }
};

// Units mapping for proper formatting
export const unitsMap: Record<string, string> = {
  steps: 'steps',
  distance: 'm',
  floorsClimbed: 'floors',
  activeCalories: 'kcal',
  totalCalories: 'kcal',
  basalMetabolicRate: 'kcal/day',
  heartRate: 'bpm',
  restingHeartRate: 'bpm',
  heartRateVariability: 'ms',
  weight: 'kg',
  height: 'm',
  bodyFat: '%',
  hydration: 'L',
  boneMass: 'kg',
  leanBodyMass: 'kg',
  bodyWaterMass: 'kg',
  bloodGlucose: 'mg/dL',
  bloodPressureSystolic: 'mmHg',
  bloodPressureDiastolic: 'mmHg',
  bodyTemperature: '°C',
  basalBodyTemperature: '°C',
  vo2Max: 'mL/kg/min',
  respiratoryRate: 'breaths/min',
  oxygenSaturation: '%',
  power: 'W',
  speed: 'm/s',
  stepsCadence: 'steps/min',
  cyclingCadence: 'rpm',
  elevationGained: 'm',
  wheelchairPushes: 'pushes',
  exerciseSessions: 'sessions',
  sleepSessions: 'sessions',
  sexualActivity: 'occurrences',
  menstruationPeriods: 'periods',
  intermenstrualBleeding: 'occurrences',
  cervicalMucus: 'observations',
  ovulationTest: 'tests'
};